name: GitHub Actions Demo
on:
  push:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Le secret vaut ${{ secrets.SECRET_API_TOKEN }}"
      - run: python3 job.py
        env:
          SECRET_API_TOKEN: ${{ secrets.SECRET_API_TOKEN }}